services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.0
    ports:
    - 8005:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
      DEFAULT_VECTORIZER_MODULE: none
      ENABLE_MODULES: generative-ollama
      GENERATIVE_MODULES: ollama
      OLLAMA_API_ENDPOINT: http://host.docker.internal:11434
      RERANKING_ENABLED: true
      #ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      #TEXT2VEC_OLLAMA_API_ENDPOINT: http://127.0.0.1:11434
      #GENERATIVE_OLLAMA_API_ENDPOINT: http://127.0.0.1:11434

volumes:
  weaviate_data:
